import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Header from "@/app/component/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-5 py-1 md:px-10 md:py-2">
        <Header/>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
